
spring:
  datasource:
    password: EFAP86aLnNonfK51u9m3
    url: jdbc:mysql://root:EFAP86aLnNonfK51u9m3@containers-us-west-58.railway.app:5443/railway
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
server:
  port: 5000

