
spring:
  datasource:
    password: 3ZsotOlXTO8QoTNGn8PE
    url: jdbc:mysql://root:3ZsotOlXTO8QoTNGn8PE@containers-us-west-130.railway.app:7047/railway
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
server:
  port: 5000

